name=PiperPico2
version=0.1.0
author=Chaiwat (your name)
maintainer=Chaiwat <your@email.com>
sentence=Hardware abstraction library for Piper Robot (Pico2 board)
paragraph=Support dual quadrature encoder, 4 motors via PCA9685 + GPIO PWM, 10-channel line sensor via MUX, servo, OLED SSD1306, voltage monitor, buzzer.
category=Other
url=https://github.com/yourname/PiperPico2
architectures=*
includes=PiperPico2.h